name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - master
      - deploy-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Invoke Webpack build
      run: |
        npm install .
        npm run build

    - name: Invoke Deployment
      with:
        ACCESS_TOKEN: ${{ f27ec0d8d27d0289c1d0e0ca85c1530d57da6df1 }}
        BRANCH: gh-pages
        FOLDER: dist
      uses: JamesIves/github-pages-deploy-action@3.2.1
